services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ../web:/var/www/php
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../nginx/fpm_pass.conf:/etc/nginx/fpm_pass.conf
    environment:
      TZ: ${TZ}

  wss:
    build:
      context: ../wss/
      dockerfile: Dockerfile
    stop_grace_period: 0s
    environment:
      TZ: ${TZ}
