server {
    listen 80;
    server_name phpfpm.local;

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    index index.html;

    root /var/www/php;
    autoindex off;

    location = / {
        return 301 /index.html;
    }

    location /ws/ {
        proxy_pass http://wss:8888/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_read_timeout 600;
        proxy_send_timeout 600;
    }
}
